[package]
authors = ["Holochain Foundation"]
edition = "2021"
name = "utilities"
version = "0.1.0"

[dependencies]
arbitrary = "1.2"
ed25519-dalek = "1"
holochain_client = {path = "../"}
holochain_state = { git="https://github.com/holochain/holochain", package = "holochain_state", rev = "96a166fce9362da635339bf14e42a8cf157bdc8f" }
holochain_zome_types = { git="https://github.com/holochain/holochain", package = "holochain_zome_types", rev = "96a166fce9362da635339bf14e42a8cf157bdc8f" }
rand = "0.7"
