[package]
authors = ["Holochain Foundation"]
edition = "2021"
name = "utilities"
version = "0.1.0"

[dependencies]
arbitrary = "1.2"
ed25519-dalek = "1"
holochain_client = {path = "../"}
holochain_state = { git="https://github.com/holochain/holochain", package = "holochain_state", rev = "352bcebe41808b0a5c58cc6f1ed1e1c96149d010" }
holochain_zome_types = { git="https://github.com/holochain/holochain", package = "holochain_zome_types", rev = "352bcebe41808b0a5c58cc6f1ed1e1c96149d010" }
rand = "0.7"
