[package]
name = "test_wasm_foo"
version = "0.0.1"
authors = ["thedavidmeister", "thedavidmeister@gmail.com"]
edition = "2021"

[lib]
name = "test_wasm_foo"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1"
hdi = { git="https://github.com/holochain/holochain", package = "hdi", rev = "96a166fce9362da635339bf14e42a8cf157bdc8f" }
hdk = { git="https://github.com/holochain/holochain", package = "hdk", rev = "96a166fce9362da635339bf14e42a8cf157bdc8f" }
